apiVersion: apps/v1
kind: Deployment
metadata:
  name: tradeapp-deployment
  labels:
     app: tradeapp
     type: back-end
spec:
  # A deployment's specification really only 
  # has a few useful options

  # This template field is a regular pod configuration 
  # nested inside the deployment spec
  template:
     metadata:
       # Set labels on the pod.
       # This is used in the deployment selector.
       name: tradeapp-pod
       labels: 
         app: tradeapp
         type: back-end
     spec:
         serviceAccountName: jenkins
         containers:
           - name: tradeapp-app
             image: "${DOCKER_REGISTRY}:${BUILD_NUMBER}"
  replicas: 1
  selector:
    matchLabels:
      type: back-end

---
apiVersion: v1
kind: Service
metadata:
  name: tradeapp-service
spec:
  selector:
    app: tradeapp
  type: LoadBalancer  
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8080
      nodePort: 8080
